@base_url=http://localhost:8081

GET {{base_url}}/tokenz
Content-Type: application/json
# @name auth

###

@token = {{auth.response.body.$.token}}

POST  {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "test 56"
}